CoCoding/apps/meetings/urls.py
from django.urls import path

from apps.meetings.views import MeetingCreateView, MeetingUpdateView, MeetingDetailView, MeetingListView, \
    MeetingStartView, MeetingMemberUpdateView, MeetingMemberDeleteView, InvitationRedirectView, MeetingDeleteView, \
    MeetingMemberTypeUpdateView

urlpatterns = [
    path('', MeetingListView.as_view(), name='list'),
    path('create/', MeetingCreateView.as_view(), name='create'),
    path('<int:pk>/', MeetingDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', MeetingUpdateView.as_view(), name='update'),
    path('<int:pk>/start/', MeetingStartView.as_view(), name='start'),
    path('<int:pk>/delete/', MeetingDeleteView.as_view(), name='delete'),
    path('<int:pk>/member_update/', MeetingMemberUpdateView.as_view(), name='member_update'),
    path('<int:pk>/member_delete/', MeetingMemberDeleteView.as_view(), name='member_delete'),
    path('<int:pk>/member_type_update/', MeetingMemberTypeUpdateView.as_view(), name='member_type_update'),
    path('invite/<hash>/', InvitationRedirectView.as_view(), name='invitation'),
]

CoCoding/apps/users/urls.py
from django.urls import path
from .views import LoginView, LogoutView, UserRegisterView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', UserRegisterView.as_view(), name='signup'),
]

CoCoding/conf/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include


def index_view(request):
    return render(request, template_name='index.html')


urlpatterns = [
    path('', index_view, name='index'),
    path('admin/', admin.site.urls),
    path('codes/', include(('apps.codes.urls', 'apps.codes'), namespace='code')),
    path('users/', include(('apps.users.urls', 'apps.users'), namespace='user')),
    path('meetings/', include(('apps.meetings.urls', 'apps.meetings'), namespace='meeting')),
]

CoCoding/templates/base.html
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}CoCoding{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <!-- Place favicon.ico in the root directory -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
    <!-- CSS here -->

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block extra_css %}
        <style>
            .modal{
                position: fixed;
                top: 0;
                right: 0;
                bottom: 0;
                left: 0;
                z-index: 1000000;
                display: none;
                overflow: hidden;
                outline: 0;
            }
        </style>
    {% endblock %}
</head>

<body>
{% block header %}
    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid">
                    <div class="row align-items-center">
                        <div class="col-xl-3 col-lg-3">
                            <div class="logo">
                                <a href="{% url 'index' %}">
                                    <h3 class="wow fadeInDown" data-wow-duration="1s" data-wow-delay=".1s" style="color : white;margin-top: 20px;font-weight: bold;">CoCoding
                                        <img src="{% static 'img/cocoding_logo.png' %}" alt="" style="width: auto; height: auto;max-width: 50px;max-height: 50px;"></h3>
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6">
                            <div class="main-menu  d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a class="active" href="{% url 'index' %}" style="font-size: 20px;">Home</a></li>
                                        <li><a href="{% url 'meeting:list' %}" style="font-size: 20px;">Meetings</a></li>
                                        <li><a href="https://github.com/COCODlNG" style="font-size: 20px;">Contact</a></li>
                                        {% if not user.is_authenticated %}
                                            <li><a href="{% url 'user:login' %}" style="font-size: 20px;">Login</a></li>
                                        {% endif %}
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                            <div class="Appointment">
                                <div class="book_btn d-none d-lg-block">
                                    {% if user.is_authenticated %}
                                        <a href="{% url 'user:logout' %}">Sign Out</a>
                                    {% else %}
                                        <a class="btn btn-primary" href="{% url 'user:login' %}">Sign In</a>
                                    {% endif %}

                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->
{% endblock %}
{% block breadcam %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{% block subtitle %}로그인{% endblock %}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /bradcam_area  -->
{% endblock %}

{% block content %}
    <!--================Blog Area =================-->

    <section class="blog_area section-padding">
        {% if messages %}
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">알림</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <ul class="messages">
                                {% for message in messages %}
                                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.message }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="genric-btn info circle" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="container">
            {% block content_container %}
            {% endblock %}
        </div>
    </section>
    <!--================Blog Area =================-->
{% endblock content %}

{% block footer %}
    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget">
                            <div class="footer_logo">
                                <a href="#">
                                    <h3 class="wow fadeInDown" data-wow-duration="1s" data-wow-delay=".1s" style="color : white;margin-top: 20px;font-weight: bold;">CoCoding
                                        <img src="{% static 'img/cocoding_logo.png' %}" alt="" style="width: auto; height: auto;max-width: 50px;max-height: 50px;"></h3>

                                </a>
                            </div>
                            <p>
                                CoCoding is Online Collaborative Coding Service
                                based on Live Streaming.
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="ti-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="ti-twitter-alt"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 offset-xl-1 col-md-6 col-lg-3">
                        <div class="footer_widget">
                            <h3 class="footer_title" style="margin-bottom: 20px;">
                                Sekyo
                            </h3>
                            <ul>
                                <img src="{% static 'img/segyo.png' %}" alt="" style="width: auto; height: auto;max-width: 150px;max-height: 150px;">
                                <li><a href="https://github.com/MyungSeKyo">good</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget">
                            <h3 class="footer_title" style="margin-bottom: 20px;">
                                Junseok
                            </h3>
                            <ul>
                                <img src="{% static 'img/junseok.png' %}" alt="" style="width: auto; height: auto;max-width: 150px;max-height: 150px;">
                                <li><a href="https://github.com/shawn159">great</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget">
                            <h3 class="footer_title" style="margin-bottom: 20px;">
                                JJaemoon
                            </h3>
                            <ul>
                                <img src="{% static 'img/jjaem.png' %}" alt="" style="width: auto; height: auto;max-width: 150px;max-height: 150px;">
                                <li><a href="https://github.com/JungChaeMoon">
                                    fancy
                                </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->
{% endblock %}

<!-- JS here -->
<script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'js/ajax-form.js' %}"></script>
<script src="{% static 'js/waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'js/scrollIt.js' %}"></script>
<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/gijgo.min.js' %}"></script>

<!--contact js-->
<script src="{% static 'js/contact.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'js/jquery.form.js' %}"></script>
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/mail-script.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>
{% block extra_js %}
    <script type="application/javascript">
        $(document).ready(function () {
            $('#exampleModal').modal({show:true})
        })
    </script>
{% endblock %}
</body>

</html>

CoCoding/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}CoCoding{% endblock %}
{% block breadcam %}{% endblock %}
{% block content %}
    {% if messages %}
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">알림</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <ul class="messages">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="genric-btn info circle" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    <!-- slider_area_start -->
    <div class="slider_area">
        <div class="single_slider  d-flex align-items-center slider_bg_1">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-7 col-md-6">
                        <div class="slider_text ">
                            <h3 class="wow fadeInDown" data-wow-duration="1s" data-wow-delay=".1s" >CoCoding<br>
                            </h3>
                            <p class="wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".1s">Let's Start CoCoding with Capstone Project~</p>
                            {% if not user.is_authenticated %}
                                <div class="video_service_btn wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".1s">
                                    <a href="{% url 'user:signup' %}" class="boxed-btn3">Sign Up</a>
                                </div>
                            {% else %}
                                <div class="video_service_btn wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".1s">
                                    <a href="{% url 'meeting:list' %}" class="boxed-btn3">Meetings</a>
                                </div>
                            {% endif %}

                        </div>
                    </div>
                    <div class="col-xl-5 col-md-6">
                        <div class="phone_thumb wow fadeInDown" data-wow-duration="1.1s" data-wow-delay=".2s">
                            <img style="width: 500px; position: relative;top: -100px" src="{% static 'img/ui.png' %}" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider_area_end -->
    <!-- service_area  -->
    <div class="service_area">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="section_title text-center  wow fadeInUp" data-wow-duration=".5s" data-wow-delay=".3s">
                        <h3>CoCoding Includes</h3>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-md-4">
                    <div class="single_service text-center wow fadeInUp" data-wow-duration=".6s" data-wow-delay=".4s">
                        <div class="thumb">
                            <img src="{% static 'img/icon/2.svg' %}" alt="">
                        </div>
                        <h3>Live Coding!</h3>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4">
                    <div class="single_service text-center wow fadeInUp" data-wow-duration=".7s" data-wow-delay=".5s">
                        <div class="thumb">
                            <img src="{% static 'img/icon/1.svg' %}" alt="">
                        </div>
                        <h3>Online Compiler!</h3>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4">

                    <div class="single_service text-center wow fadeInUp " data-wow-duration=".8s" data-wow-delay=".6s">
                        <div class="thumb">
                            <img src="{% static 'img/icon/3.svg' %}" alt="">
                        </div>
                        <h3>Live Video Chat</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ service_area  -->
{% endblock content %}