CoCoding/apps/meetings/urls.py
from django.urls import path

from apps.meetings.views import MeetingCreateView, MeetingUpdateView, MeetingDetailView, MeetingListView, \
    MeetingStartView, MeetingMemberUpdateView, MeetingMemberDeleteView, InvitationRedirectView, MeetingDeleteView, \
    MeetingMemberTypeUpdateView

urlpatterns = [
    path('', MeetingListView.as_view(), name='list'),
    path('create/', MeetingCreateView.as_view(), name='create'),
    path('<int:pk>/', MeetingDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', MeetingUpdateView.as_view(), name='update'),
    path('<int:pk>/start/', MeetingStartView.as_view(), name='start'),
    path('<int:pk>/delete/', MeetingDeleteView.as_view(), name='delete'),
    path('<int:pk>/member_update/', MeetingMemberUpdateView.as_view(), name='member_update'),
    path('<int:pk>/member_delete/', MeetingMemberDeleteView.as_view(), name='member_delete'),
    path('<int:pk>/member_type_update/', MeetingMemberTypeUpdateView.as_view(), name='member_type_update'),
    path('invite/<hash>/', InvitationRedirectView.as_view(), name='invitation'),
]

CoCoding/conf/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include


def index_view(request):
    return render(request, template_name='index.html')


urlpatterns = [
    path('', index_view, name='index'),
    path('admin/', admin.site.urls),
    path('codes/', include(('apps.codes.urls', 'apps.codes'), namespace='code')),
    path('users/', include(('apps.users.urls', 'apps.users'), namespace='user')),
    path('meetings/', include(('apps.meetings.urls', 'apps.meetings'), namespace='meeting')),
]

CoCoding/apps/meetings/models.py
from django.db import models
from django.urls import reverse_lazy
from django_extensions.db.fields.json import JSONField
from django_extensions.db.models import TimeStampedModel
from hashid_field import HashidField


class MeetingMemberRelation(TimeStampedModel):
    meeting = models.ForeignKey('meetings.Meeting', on_delete=models.CASCADE, null=False)
    member = models.ForeignKey('users.User', on_delete=models.CASCADE, null=False)
    MEMBER_MANAGER, MEMBER_STUDENT = 'manager', 'student'
    MEMBER_TYPE_CHOICES = (
        (MEMBER_MANAGER, '관리자'),
        (MEMBER_STUDENT, '학생'),
    )
    member_type = models.CharField(max_length=10, choices=MEMBER_TYPE_CHOICES, null=False, default=MEMBER_STUDENT)
    code = JSONField()

    class Meta:
        unique_together = [['meeting', 'member'], ]

    def is_admin(self):
        return self.member_type == self.MEMBER_MANAGER

    def is_admin_template(self):
        return 'true' if self.is_admin() else 'false'


class Meeting(TimeStampedModel):
    title = models.CharField(max_length=30, default='Untitled')
    description = models.TextField(blank=True, default='Enter the description')
    host = models.ForeignKey('users.User', on_delete=models.CASCADE, related_name='+')
    members = models.ManyToManyField('users.User', related_name='meetings', through='meetings.MeetingMemberRelation')
    url_hash = HashidField(null=True)
    is_ongoing = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super(Meeting, self).save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields,
        )
        MeetingMemberRelation.objects.get_or_create(
            member=self.host,
            meeting=self,
            member_type=MeetingMemberRelation.MEMBER_MANAGER
        )

    def get_detail_url(self):
        return reverse_lazy('meeting:detail', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse_lazy('meeting:update', kwargs={'pk': self.pk})

    def get_start_url(self):
        return reverse_lazy('meeting:start', kwargs={'pk': self.pk})

    def get_invitation_url(self):
        return reverse_lazy('meeting:invitation', kwargs={'hash': self.url_hash})

CoCoding/apps/meetings/forms.py
from django import forms

from apps.meetings.models import Meeting


class MeetingForm(forms.ModelForm):

    class Meta:
        fields = ['title', 'description']
        model = Meeting

CoCoding/apps/meetings/views.py
from django.http import HttpResponseForbidden, JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, reverse
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, RedirectView, DetailView, View
from django.views.generic.edit import BaseUpdateView, DeleteView
from django.contrib import messages
from apps.meetings.forms import MeetingForm
from apps.meetings.models import Meeting, MeetingMemberRelation
from apps.users.models import User
from core.views import CheckUserMixin


class MeetingListView(CheckUserMixin, ListView):
    model = Meeting
    template_name = 'meeting_list.html'

    def get_queryset(self):
        return self.request.user.meetings.all()


class MeetingUpdateView(CheckUserMixin, UpdateView):
    model = Meeting
    template_name = 'meeting_form.html'
    form_class = MeetingForm

    success_url = reverse_lazy('meeting:list')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.url_hash is None:
            self.object.url_hash = self.object.pk
            self.object.save()
        return super(BaseUpdateView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MeetingUpdateView, self).get_context_data(**kwargs)
        context['relations'] = MeetingMemberRelation.objects.select_related('member').filter(meeting=self.object)
        return context


class MeetingCreateView(CheckUserMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        meeting = Meeting(host=self.request.user)
        meeting.save()
        return reverse_lazy('meeting:update', kwargs={'pk': meeting.pk})


class MeetingDetailView(CheckUserMixin, DetailView):
    model = Meeting
    template_name = 'meeting_detail.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.relation = MeetingMemberRelation.objects.filter(meeting=self.object, member=self.request.user).first()
        if not self.relation:
            return HttpResponseForbidden()

        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(MeetingDetailView, self).get_context_data(**kwargs)
        context['relation'] = self.relation
        return context


class MeetingStartView(CheckUserMixin, RedirectView):
    meeting = None

    def setup(self, request, *args, **kwargs):
        super(MeetingStartView, self).setup(request, *args, **kwargs)
        self.meeting = get_object_or_404(Meeting, pk=kwargs['pk'])

    def dispatch(self, request, *args, **kwargs):
        if self.request.user == self.meeting.host:
            self.meeting.is_ongoing = True
            self.meeting.save(update_fields=['is_ongoing'])
        else:
            return HttpResponseForbidden()
        return super(MeetingStartView, self).dispatch(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('meeting:detail', kwargs={'pk': self.meeting.id})


class MeetingDeleteView(CheckUserMixin, DeleteView):

    model = Meeting
    success_url = reverse_lazy('meeting:list')
    meeting = None

    def get(self, request, *args, **kwargs):
        self.meeting = get_object_or_404(Meeting, pk=kwargs['pk'])
        if self.request.user == self.meeting.host:
            return self.post(request, *args, **kwargs)
        else:
            return reverse_lazy('meeting:list')


class MeetingMemberUpdateView(View):

    pk_url_kwarg = 'pk'
    meeting = None
    user = None
    meeting_member_relation = None

    def post(self, request, *args, **kwargs):
        username = request.POST.get('id_member')

        self.user = get_object_or_404(User, username=username)
        self.meeting = get_object_or_404(Meeting, pk=kwargs['pk'])
        try:
            self.meeting_member_relation = MeetingMemberRelation.objects.create(meeting=self.meeting, member=self.user)
            self.meeting_member_relation.member_type = MeetingMemberRelation.MEMBER_STUDENT
            self.meeting_member_relation.save()
        except Exception:
            context = {
                'message': 'unique',
                'error': '이미 추가한 아이디입니다.',
            }
            return JsonResponse(context, json_dumps_params={'ensure_ascii': True})
        context = {
            'user_id': self.user.id,
            'user_name': self.user.username,
            'user_type': '학생',
            }
        return JsonResponse(context, json_dumps_params={'ensure_ascii': True})


class MeetingMemberDeleteView(View):

    pk_url_kwarg = 'pk'
    meeting = None
    user = None

    def post(self, request, *args, **kwargs):

        user_pk = request.POST.get('delete_id')

        self.user = get_object_or_404(User, pk=user_pk)
        self.meeting = get_object_or_404(Meeting, pk=kwargs['pk'])
        try:
            MeetingMemberRelation.objects.filter(meeting=self.meeting, member=self.user).delete()
        except Exception:
            context = {
                'message': 'already',
                'error': '이미 삭제한 아이디입니다.',
            }
            return JsonResponse(context, json_dumps_params={'ensure_ascii': True})
        return HttpResponse(status=200)


class InvitationRedirectView(CheckUserMixin, RedirectView):

    meeting = None
    meeting_relation = None

    def setup(self, request, *args, **kwargs):
        super(InvitationRedirectView, self).setup(request, *args, **kwargs)
        self.meeting = get_object_or_404(Meeting, url_hash=kwargs['hash'])

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            hash_value = str(kwargs['hash'])
            login_url = reverse('user:login')
            return redirect(login_url + '?hash=' + hash_value)

        try:
            MeetingMemberRelation.objects.create(meeting=self.meeting, member=self.request.user)
        except Exception:
            messages.add_message(self.request, messages.WARNING, '이미 참가하고 있는 미팅입니다.')
            return HttpResponseRedirect(reverse_lazy('meeting:list'))

        return super(InvitationRedirectView, self).dispatch(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        messages.add_message(self.request, messages.INFO, '이제 미팅에 참여 할 수 있습니다.')
        return reverse_lazy('meeting:list')


class MeetingMemberTypeUpdateView(CheckUserMixin, View):

    pk_url_kwarg = 'pk'
    user = None
    meeting = None
    meeting_member_relation = None

    def get(self, request, *args, **kwargs):
        user_id = int(request.GET.get('user_id'))
        self.meeting = get_object_or_404(Meeting, pk=kwargs['pk'])
        self.user = get_object_or_404(User, pk=user_id)
        if request.user == self.meeting.host:
            self.meeting_member_relation = MeetingMemberRelation.objects.get(meeting=self.meeting, member=self.user)
            if self.meeting_member_relation.member_type == 'manager':
                self.meeting_member_relation.member_type = MeetingMemberRelation.MEMBER_STUDENT
            else:
                self.meeting_member_relation.member_type = MeetingMemberRelation.MEMBER_MANAGER
            self.meeting_member_relation.save()
            return HttpResponseRedirect(reverse_lazy('meeting:update', kwargs={'pk': kwargs['pk']}))

CoCoding/apps/meetings/templates/meeting_form.html
{% extends 'base.html' %}
{% block extra_css %}
    <style>
        .modal{
            position: fixed;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            z-index: 1000000;
            display: none;
            overflow: hidden;
            outline: 0;
        }
        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown:hover .dropdown-content {
            display: block;
        }
    </style>
{% endblock %}
{% block subtitle %}
    <h3 class="wow fadeInDown" data-wow-duration="1s" data-wow-delay=".1s" style="visibility: visible; animation-duration: 1s; animation-delay: 0.1s;">
        미팅관리
    </h3>
{% endblock %}
{% block content_container %}
    <div class="row">
        <div class="row col-sm-12">
        <div class="col-sm-6">
            <h1 class="contact-title">미팅에 멤버를 추가해주세요!</h1>
        </div>
        <div class="col-sm-6">

            <button type="button" class="genric-btn info circle" data-toggle="modal" data-target="#exampleModal">Invitation Link</button>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Invitation Link</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>
                            <h4>링크를 공유해 멤버들을 초대해 보세요!</h4>
                            </p>
                            <p>
                                {{ request.get_host }}{{ object.get_invitation_url }}
                            </p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="genric-btn info circle" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
        <div class="row col-sm-12">
            <div class="col-sm-6">
                <form class="form-contact contact_form" action="." method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_title">Title:</label>
                        <input class="form-control valid" name="title" maxlength="30" required id="id_title" value="{{ object.title }}" type="text" placeholder="입력해주세요">
                    </div>
                    <div class="form-group">
                        <label for="id_description">Description:</label>
                        <textarea class="form-control w-100" name="description" required id="id_description" cols="40" rows="10" placeholder="입력해주세요">{{ object.description }}</textarea>
                    </div>
                    <button class="genric-btn info circle">완료</button>
                </form>
            </div>
            <div class="col-sm-6">

                <label for="id_member">Member Search:</label>
                <div class="input-group">
                    <input class="form-control valid" name="id_member" maxlength="30" required id="id_member" value="" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter the member'" placeholder="Enter the member">
                    <div class="input-group-append">
                        <button class="search-button genric-btn info circle" type="button" style="border-top-left-radius: 0; border-bottom-left-radius: 0">검색</button>
                    </div>
                </div>

                <div class="section-top-border" style="margin-top: 15px;">
                    <div class="progress-table-wrap">
                        <div class="progress-table" style="min-width: 0;">
                            <div class="table-head">
                                <div class="serial col-lg-1 col-md-2">#</div>
                                <div class="visit col-lg-4 col-md-6" type="text">Name</div>
                                <div class="country col-lg-4 col-md-6" type="text" style="width: 0;">Member type</div>
                            </div>
                            {% for relation in relations %}
                                <div class="table-row">
                                    <div class="serial col-lg-1 col-md-2" type="text" style="width: 11.83%; padding-left: 30px;">{{ relation.member.id }}</div>
                                    <div class="visit col-lg-4 col-md-6" type="text" style="width: 17.74%;">{{ relation.member.username }}</div>
                                    <div class="country col-lg-3 col-md-4" style="width: 19.74%;">{{ relation.member_type }}</div>
                                    <div class="dropdown col-lg-2 col-md-3">
                                        <i class="fa fa-ellipsis-v" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" aria-hidden="true" style="text-align: center; width: 50px;"></i>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            <a class="delete dropdown-item" data-pk="{{ relation.member.id }}">삭제</a>
                                            {% if relation.member_type == 'student' %}
                                                <a class="manager dropdown-item" href="javascript: memberTypeManager()" data-type="manager" data-pk="{{ relation.member.id }}" style="color: black">관리자로 지정</a>
                                            {% else %}
                                                <a class="student dropdown-item" href="javascript: memberTypeStudent()" data-type="student" data-pk="{{ relation.member.id }}" style="color: black">권한 회수</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% block extra_js %}
        <script type="text/javascript">
            function newAlert (name){
                alert(name);
                return false;
            }
            $(document).ready(function () {
                $('.search-button').click(function () {
                        var username = $('#id_member').val()
                        $.ajax({
                            type: 'POST',
                            url: '{% url 'meeting:member_update' object.pk %}',
                            dataType: 'json',
                            data: {
                                csrfmiddlewaretoken: '{{ csrf_token }}',
                                'id_member': username
                            },
                            success: function (res) {
                                window.location.reload();
                                if(res['message'])
                                    newAlert(res['error']);

                                else {
                                    {#var user_id = res['user_id'];#}
                                    {#var user_name = res['user_name'];#}
                                    {#var user_type = res['user_type']#}
                                    {#$('.progress-table').append(#}
                                    {#    '<div class="table-row">\n' +#}
                                    {#    '                                <div class="serial" type="text" style="width: 11.83%; padding-left: 30px;">'+ user_id +'</div>\n' +#}
                                    {#    '                                <div class="country" type="text" style="width: 17.74%;">'+ user_name +'</div>\n' +#}
                                    {#    '                                <div class="visit" style="width: 19.74%;">'+ user_type +'</div>\n' +#}
                                    {#    ' <div class="dropdown">\n' +#}
                                    {#    '            <i class="fa fa-ellipsis-v" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" aria-hidden="true"></i>\n' +#}
                                    {#    '            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">\n' +#}
                                    {#    '                <a class="delete dropdown-item" href="javascript: " data-pk="'+user_id+'">삭제</a>\n' +#}
                                    {#    '                <a class="update dropdown-item" data-pk="'+user_id+'">관리자로 승격</a>\n' +#}
                                    {#    '            </div>\n' +#}
                                    {#    '        </div>                               ' +#}
                                    {#    '                            </div>'#}
                                    {#)#}
                                }
                            },
                            error: function (error) {
                                newAlert('존재 하지 않는 아이디입니다.');
                            }
                        });
                    }
                )
            })

            $('body').on('click', '.table-row .dropdown .dropdown-menu .delete', function () {
                var serial = $(this).data('pk');
                $.ajax({
                    type: 'POST',
                    url: '{% url 'meeting:member_delete' object.pk%}',
                    dataType: 'json',
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        'delete_id': serial
                    },
                    success: function (res) {
                        window.location.reload()
                    },
                    error: function (error) {
                        window.location.reload()
                    },
                })
            })

            $('body').on('click', '.table-row .dropdown .dropdown-menu .manager', function () {
                if(confirm('관리자로 지정하시겠습니까?')){
                    var user_id = $(this).attr('data-pk')
                    var update_url = '{% url 'meeting:member_type_update' object.pk %}?user_id=' +user_id;
                    location.href = update_url;
                }
            })

            $('body').on('click', '.table-row .dropdown .dropdown-menu .student', function () {
                if(confirm('학생으로 지정하시겠습니까?')){
                    var user_id = $(this).attr('data-pk')
                    var update_url = '{% url 'meeting:member_type_update' object.pk %}?user_id=' +user_id;
                    location.href = update_url;
                }
            })


        </script>
    {% endblock %}
{% endblock %}

CoCoding/apps/meetings/templates/meeting_list.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
    <style>
        .genric-btn.primary {
            color: #fff;
            background: orange;
            border: 1px solid transparent;
        }
        .genric-btn.primary:hover {
            color: orange;
            border: 1px solid orange;
            background: #fff;
        }
    </style>
{% endblock %}
{% block breadcam %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12 row">
                    <div class="bradcam_text col-xl-8">
                        {% block subtitle %}<h3 class="wow fadeInDown" data-wow-duration="1s" data-wow-delay=".1s" style="visibility: visible; animation-duration: 1s; animation-delay: 0.1s;">미팅 리스트</h3>{% endblock %}
                    </div>
                    <div class="col-xl-4">
                        <a class="genric-btn info-border circle" href="{% url 'meeting:create' %}">미팅 만들기</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /bradcam_area  -->
{% endblock %}
{% block content_container %}

    <div class="row">
        {% for meeting in object_list %}
            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                <div class="wow fadeInDown" data-wow-duration="1s" data-wow-delay=".1s" style="visibility: visible; animation-duration: 1s; animation-delay: 0.1s;">

                    <article class="blog_item">
                        <div class="blog_details" style="border: 1px; solid-color: #1b2426">
                            <div style="display: flex;">
                                <a class="d-inline-block" href="{{ meeting.get_start_url }}">
                                    <h2>{{ meeting.title }}&nbsp;&nbsp;</h2>
                                </a>
                                <span>{{ meeting.host }}교수님</span>
                            </div>
                            <p style="justify-content: center">{{ meeting.description }}</p>
                            <ul class="blog-info-link">
                                {% if meeting.host == user %}
                                    <div style="display: flex">
                                        <ul class="blog-info-link" style="padding-top: 20px;">
                                            <li><a href="{% url 'meeting:update' meeting.pk %}"><i class="fa fa-user"></i>미팅 관리</a></li>
                                            <li><a href="javascript: if(confirm('삭제하시겠습니까??')){location.href='{% url 'meeting:delete' meeting.pk %}'}"><i class="fa fa-comments"></i>미팅 삭제</a></li>
                                        </ul>
                                        <button onclick="location.href='{{ meeting.get_start_url }}'" class="genric-btn primary circle" style="margin-left: auto;" >미팅 시작</button>
                                    </div>
                                {% else %}
                                    {% if meeting.is_ongoing %}
                                        <div style="display: flex">
                                            <input type="hidden" value="#">
                                            <button onclick="location.href='{{ meeting.get_detail_url }}'" class="genric-btn primary circle" style="margin-left: auto">미팅 참가</button>
                                        </div>
                                    {% else %}
                                        <div style="display: flex">
                                            <input type="hidden" value="#">
                                            <a href="" class="genric-btn primary circle" style="margin-left: auto">미팅 참가</a>
                                        </div>
                                    {% endif %}
                                {% endif %}
                            </ul>
                        </div>
                    </article>
                </div>
            </div>
        {% empty %}
            <h1>미팅이 없습니다.</h1>
        {% endfor %}
    </div>

{% endblock %}